name: Fix typos nightly

on:
  workflow_dispatch: {} # enable manual running of workflow.
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: sobolevn/misspell-fixer-action@8842a5615f83fed75e8a87015e9300a54d049961
      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: fixes by misspell-fixer"
          title: "chore: typos fix by misspell-fixer"
          branch: "bot/fix-typos"
          delete-branch: true
          body: |
            This PR fixes typos in the codebase.
            Please, review it and merge if everything is fine.
            If there are proto changes, please, run `make proto-all` and commit changes.
